name: SecretShield

on:
  push:
  pull_request:

jobs:
  secretshield:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install SecretShield 0.6.0
        run: |
             python -m pip install secretshield
             ss --version
             ss scan-staged
             python -m pip uninstall -y secretshield
             python -m pip install secretshield==0.6.0
             ss --version
             python -m pip uninstall -y secretshield
             python -m pip install secretshield==0.5.2
             ss --version
             python -m pip uninstall -y secretshield

      - name: Install Latest Version of SecretShield
        run: |
             python -m pip install secretshield

      - name: Scan repository
        run: |
            secretshield scan .
             python -m pip uninstall -y secretshield
             python -m pip install secretshield
             ss --creator
             ss scan shell.py
             python -m pip uninstall -y secretshield
